name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Git 저장소 체크아웃
      - uses: actions/checkout@v3

      # JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Gradle 캐싱 (빌드 시간 단축)
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 환경별 yml 파일 생성 - prod
      - name: make application-prod.yml
        run: |
          mkdir -p src/main/resources  # ✅ 디렉터리 없으면 생성
          echo "${{ secrets.YML }}" > src/main/resources/application-prod.yml
          ls -al src/main/resources  # ✅ 파일이 정상적으로 생성되었는지 확인
        shell: bash

      # Gradle 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Gradle 빌드
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # ENV_FILE 확인
      - name: Debug ENV_FILE
        run: |
          echo "${{ secrets.ENV_FILE }}"

      # Compose 빌드
      - name: Docker Compose Build
        run: |
          printf "${{ secrets.ENV_FILE }}" > .env
          docker compose build

      # Docker Hub 로그인
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Docker Compose 빌드
      - name: Docker Compose Build
        run: |
          docker compose build

      # 빌드된 이미지 확인 (디버깅용)
      - name: List Docker images
        run: |
          docker images

      - name: Docker Tag Images
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/my-server:latest ${{ secrets.DOCKER_USERNAME }}/my-server:latest

      - name: Docker Push My-Server Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-server:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # 깃허브 레포지토리 코드 다운로드
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ 파일이 실제로 존재하는지 확인하는 단계 추가
      - name: Check docker-compose.yml existence
        run: ls -al

      # 파일 복사
      - name: Copy docker-compose.yml to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "~/app/"  # 서버의 저장 경로

      # 서버에 배포
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }} # EC2 퍼블릭 IP
          username: ${{ secrets.USERNAME }}   # 홈서버 SSH 계정 (ex: ubuntu)
          key: ${{ secrets.PRIVATE_KEY }}  # PEM 키
          script: |
            cd ~/app
            
            # Create .env file
            printf "${{ secrets.ENV_FILE }}" > .env
            
            # 1️⃣ 최신 Docker 이미지 풀
            docker compose pull
            # 2️⃣ 이전 컨테이너 삭제
            sudo docker compose down
            # 3️⃣ 컨테이너와 서비스를 Docker Compose로 실행
            sudo docker compose up -d
            # 4️⃣ 불필요한 이미지 삭제
            sudo docker image prune -f